# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

dbpostgres:
    type: postgresql:12
    disk: 256

# Uncomment the line below if you would like to use a mysql database
# dbmysql:
#   type: oracle-mysql:8.0
#   disk: 256
