prepareInstall:
    type: prepareInstall
    description: 'Prepare installation'

environmentAndFolders:
    type: install
    description: 'Check environment and create folders'

extensionSetup:
    type: extensionSetup
    description: 'Set up extensions'
    commands:
        - command: 'install:generatepackagestates'
        - command: 'database:updateschema'
        - command: 'extension:setupactive'
