# The services of the project.
#
# Each service listed will be deployed to power your project.

db:
    type: oracle-mysql:8.0
    disk: 1024
search:
    type: elasticsearch:7.7
    disk: 512
jobs:
    type: network-storage:1.0
    disk: 128
